### ISSUE TITLE
Slack badge displayed in README

### ISSUE THREAD

**Issue by alexjpwalker** [graknlabs/graql#138]
## Problem to Solve

A Slack badge is displayed in the README.

## Proposed Solution

Replace the Slack badge with a Discord badge, like we have in the `grakn` repo.

**Comment by lolski** [comment]
[Triaged] @haikalpribadi I am moving it to 2.0 production with priority medium.

**Comment by haikalpribadi** [comment]
LOL.

@alexjpwalker this issue is so small, you could have just edited the readme through GitHub and push a commit directly which will automatically open a PR for you :) - and it would be faster than opening this issue.

@lolski this issue is so small, you could have just clicked on the repo page and noticed that it's already fixed, and close this issue.

So in conclusion: I'm closing this issue as it's already fixed.
